apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traffic-simulator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/uh-heung-crew/study-gitops.git'
    targetRevision: HEAD
    path: charts/traffic-simulator
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: study
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
